version: '3'

networks:
  jenkins-network:
    name: jenkins-network
    external: true

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.401.2-1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins-network
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000